apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: processed-data
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
