experiment:
  image: jsoychak/experiment-sklearn
  parameters:
    name: vgg16_log_reg
    model_name: logistic_regression
    train_path: /data/vgg16/train_data.csv
    test_path: /data/vgg16/test_data.csv
