apiVersion: v1
kind: PersistentVolume
metadata:
  name: experiments-db-volume
  namespace: team-project
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 16Gi
  local:
    path: /home/jsoychak/cs/team_project/data/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["worker0"]