apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-volume
spec:
  capacity:
    storage: 8Gi
  claimRef:
    name: logs-claim
    namespace: team-project
  accessModes:
  - ReadWriteMany
  local:
    path: /home/jsoychak/cs/team_project/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["worker0"]
  volumeMode: Filesystem
