apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: processed-data-claim
  namespace: team-project
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
