apiVersion: v1
kind: PersistentVolume
metadata:
  name: processed-data-volume
  namespace: team-project
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  hostPath:
    path: /mnt/data/processed
  