apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: processed-data
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-csi
