apiVersion: v1
kind: PersistentVolume
metadata:
  name: processed-data-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  claimRef:
    name: processed-data-claim
    namespace: team-project
  local:
    path: /home/jsoychak/cs/team_project/data/processed
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["worker0"]
  volumeMode: Filesystem