apiVersion: v1
kind: PersistentVolume
metadata:
  name: raw-data-volume
  namespace: team-project
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: /home/jsoychak/cs/team_project/data/raw
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["worker0"]
