apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-data-claim
  namespace: team-project
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
