apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-claim
  namespace: team-project
spec:
  resources:
    requests:
      storage: 32Gi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
